# -*- coding: utf-8 -*-
"""array_diff.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hawMJjoTg-aMSzQgDuj99DMMxXlmOi4Q
"""

def array_diff(a, b):
    b = set(b)
    return [x for x in a if x not in b]

