# -*- coding: utf-8 -*-
"""maskify.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hawMJjoTg-aMSzQgDuj99DMMxXlmOi4Q
"""

def maskify(cc):
    return "#" * max(len(cc) - 4, 0) + cc[-4:]
    pass

