# -*- coding: utf-8 -*-
"""square_digits

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hawMJjoTg-aMSzQgDuj99DMMxXlmOi4Q
"""

def square_digits(num):
    result = ""

    for digit in str(num):
        result += str(int(digit) ** 2)

    return int(result)

